### ISSUE TITLE
Agregar el merchant_uuid al pago

### ISSUE THREAD

**Issue by dennisbr91** [JosueCarballo/enzona_api#1]
saludos colegas, estoy usando el paquete, y me he dado cuenta que cuando tenemos mas de 1 negocio, y estamos usando la API de pago, si no le pasamos el merchant_uuid nos devuelve comercio inexistente, seria bueno actualizar el paquete para siempre pasarle este valor

**Comment by NoxCreation** [comment]
Hola Denis. Llevo 3 años o más sin las credenciales de enzona, por eso no he podido seguir dando continuidad al proyecto. En agosto haré el pedido nuevamente pero el otorgamiento suele demorar. Si me puedes ayudar sería muy bueno para toda la comunidad.

**Comment by dennisbr91** [comment]
De que manera pudiera ayudarte, busque una solución pero rústica, seria bueno cambiar el código para que sea un trabajo limpio, agregame a colaboradores y modifico lo necesario

**Comment by NoxCreation** [comment]
Ya te agregué Denis. Un gusto de tenerte de colaborador.

**Comment by dennisbr91** [comment]
Muchas gracias, ya me pongo en ello y le hago un commit, revisas la solución y hago el push

**Comment by dennisbr91** [comment]
hice los cambios y el commit al repo de aca de github, pero el paquete como tal de python se mantiene igual, eso creo que si deberia compilarlo usted

**Comment by NoxCreation** [comment]
Hecho pana https://pypi.org/project/enzona-api/

**Comment by dennisbr91** [comment]
Por favor escribame al correo dennisbr@nauta.cu, si no es resulta una molestia
